Every function of numpy works on array

In [48]:
import numpy as np
import time

In [49]:
# list vs numpy
lst = [2, [4], 5, ord, range(100)]
ans = lst[1]
ans.append(100)
print(lst)

[2, [4, 100], 5, <built-in function ord>, range(0, 100)]


In [50]:
data = range(1, 1000000)
lst = list(data)
arr = np.array(data)

In [51]:
start = time.time()
res = [i*2 for i in lst]
stop = time.time()
duration = stop - start
print('List time', duration)

start = time.time()
res2 = arr*2
stop = time.time()
duration = stop - start
print('Array time', duration)


List time 0.12105011940002441
Array time 0.005329608917236328


In [52]:
data = [2, 4, 5, 127]
arr = np.array(data, dtype='int8')
print('Array', type(arr[0]))
print('List', type(data[0]))

Array <class 'numpy.int8'>
List <class 'int'>


In [53]:
time.time()

1744347876.3852842

In [54]:
## numpy array

'''
ndArray = np.array(data[sequential])

'''

'\nndArray = np.array(data[sequential])\n\n'

In [55]:
import numpy as np
data = range(1, 10)
arr = np.array(data, dtype=complex)
print(arr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]


In [56]:
lst = [1, 3, 5, 6, 8]
arr2 = np.array(lst, ndmin=2)
print(arr2)
print('Dimension', arr2.ndim)
print('Shape', arr2.shape)

[[1 3 5 6 8]]
Dimension 2
Shape (1, 5)


In [57]:
lst = [2, 3, 4, 5, 6, 7, 8, 1, 5]
arr = np.array(lst, dtype='int8')
print(arr)
print(type(arr[0]))
arr.shape = 9, 1
print(arr)

[2 3 4 5 6 7 8 1 5]
<class 'numpy.int8'>
[[2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [1]
 [5]]


In [58]:
## arange(start, stop, step)
data = np.arange(1, 10, 0.5)
print(list(data))

[np.float64(1.0), np.float64(1.5), np.float64(2.0), np.float64(2.5), np.float64(3.0), np.float64(3.5), np.float64(4.0), np.float64(4.5), np.float64(5.0), np.float64(5.5), np.float64(6.0), np.float64(6.5), np.float64(7.0), np.float64(7.5), np.float64(8.0), np.float64(8.5), np.float64(9.0), np.float64(9.5)]


In [59]:
# linepace(start, stop, number of sample)
data = np.linspace(1, 2, 3)
print(data)

[1.  1.5 2. ]


In [60]:
data = np.array([1, 20000, 4])
print(data)

[    1 20000     4]


In [65]:
## benefit of array - searching and sorting
## on .5 it gives even priority (odd->even, even->even)
arr = np.array([2.5, 3.45, 5.45456])
val = 4.6
print(np.around(arr, 1))
round(val)

[2.5 3.4 5.5]


5

In [ ]:
## matrix

M1 = [[1, 2, 3], [3, 4, 6]]
M2 = [[0, 3, 4], [4, 5, 6]]

arr1 = np.array(M1)
arr2 = np.array(M2)

if arr1.shape == arr2.shape:
    res = np.add(arr1, arr2)
    print('\nMatrix1')
    print(arr1)
    print('\nMatrix2')
    print(arr2)
    print('\nAddition')
    print(res)
else:
    print('Not valid dimension for addition')




Matrix1
[[1 2 3]
 [3 4 6]]

Matrix2
[[0 3 4]
 [4 5 6]]

Addition
[[ 1  5  7]
 [ 7  9 12]]
